# Generated by Django 5.2 on 2025-07-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('website', models.URLField()),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referral_link', models.URLField(blank=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
