# Generated by Django 5.2 on 2025-04-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('volume_24h', models.BigIntegerField(blank=True, null=True)),
                ('percent_change_24h', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
